# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ba9010e862c49ac7e2bf2d3b0f22dba54f8a8f2be0ed638362beb7633a6d60cbdccb675225ef4c6ff1570e9c20a9bbb4ba78c2f4e90cb4c82debffd9705e136d

test:
  secret_key_base: 98b20f2ea793609a84cd48ccc563aa76d883386dcdc894ea6d63dfac87b2fe719869fff3ed78ba3dafecd416cac1b224b038b5fa1273aef57119fb6c9939a2ca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
